repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5
  hooks:
  - id: terraform_fmt
  - id: terraform_docs
  - id: terraform_tflint
  - id: terraform_validate
  - id: terraform_checkov
    args:
    - --args=--quiet
    - --args=--skip-check CKV_AWS_1
  - id: terraform_tfsec

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
  - id: changelogs
    name: Check for CHANGELOG updates
    entry: bash -c 'git diff --name-only --cached | grep -q "CHANGELOG.md"'
    language: system
    pass_filenames: false
    always_run: true
